# Copyright (C) 2023 Patrice Congo <@congop>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-go@v4.1.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      #- name: Run linters
      #  uses: golangci/golangci-lint-action@v3.6.0 
      #  with:
      #    version: latest

  generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-go@v4.1.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  # Run acceptance tests in a matrix with Terraform CLI versions
  test:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.5.*'
    steps:
      - uses: actions/checkout@v3.5.3 
      - uses: actions/setup-go@v4.1.0 
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - run: go build -o githubtools/main/saya-installer githubtools/main/main.go
      - run: sudo githubtools/main/saya-installer
      # - run: sudo systemctl list-units vbox*
      # - run: sudo modprobe vboxnetadp || true
      # - run: sudo systemctl start vboxdrv vboxautostart-service
      # - run: VBoxManage list hostonlyifs
      - run: mkdir -p '${GITHUB_WORKSPACE}/.tmp/.forge'
      - run: saya image build -t webserver:v1 ./webserverv1 --compute-type qemu --log-level debug --platform linux/arm64
        env:
          SAYA_FORGE: ${{ github.workspace }}/.tmp/.forge
      - env:
          TF_ACC: "1"
          TF_LOG: "trace"
          TF_SAYA_FORGE_WITH_IMG: ${{ github.workspace }}/.tmp/.forge
        # run: go test -v -cover ./internal/provider/
        run: go test -v -cover ./...
        # run: go test ./... -run TestAccExampleDataSource
        timeout-minutes: 30
